# nginx:
#     image: nginx:alpine
#     volumes:
#         - ./client:/usr/share/nginx/html
#     ports:
#         - "80:80"

# server:
#     build: ./main
#     ports:
#         - "8080:8080"

node:
    build: ./node-server
    command: gulp start
    ports:
        - "8080:8080"
    volumes:
        - ./node-server:/app
        - /app/node_modules
